indices:
  rh: [0, 1, 2]
  lh: [3, 4, 5]
  lf: [6, 7, 8]
  rf: [9, 10, 11]

legs:
  lf:
    flip: false
    coupled: true
  rf:
    flip: false
    coupled: true
  lh:
    flip: false   # Set to true if strafe is mirrored again
    coupled: true
  rh:
    flip: false   # Set to true if strafe is mirrored again
    coupled: true